title = "Template recipe"

description ="""
  Template recipe
  """

[agpVersion]
min = "8.2.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    "debugTemplateRecipe",
    "releaseTemplateRecipe"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
]
